<?php

namespace ContainerPuoMt34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FJr0i09Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fJr0i09' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fJr0i09'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'roleRepo' => ['privates', 'App\\Repository\\RolesRepository', 'getRolesRepositoryService', true],
        ], [
            'encoder' => '?',
            'manager' => '?',
            'roleRepo' => 'App\\Repository\\RolesRepository',
        ]);
    }
}
