<?php

namespace ContainerPuoMt34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MbMnECaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mbMnECa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mbMnECa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'couleur' => ['privates', '.errored..service_locator.mbMnECa.App\\Entity\\Couleur', NULL, 'Cannot autowire service ".service_locator.mbMnECa": it references class "App\\Entity\\Couleur" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'couleur' => 'App\\Entity\\Couleur',
            'manager' => '?',
        ]);
    }
}
