<?php

namespace ContainerPuoMt34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MbfwckyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mbfwcky' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mbfwcky'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'acceuilRepo' => ['privates', 'App\\Repository\\AcceuilRepository', 'getAcceuilRepositoryService', true],
            'cacheManager' => ['services', 'liip_imagine.cache.manager', 'getLiipImagine_Cache_ManagerService', false],
            'catRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'acceuilRepo' => 'App\\Repository\\AcceuilRepository',
            'cacheManager' => '?',
            'catRepo' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
