<?php

namespace ContainerPuoMt34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HKZXyzvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HKZXyzv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HKZXyzv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::AjoutCategorie' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AdminController::AjoutCouleur' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AdminController::AjoutOeuvre' => ['privates', '.service_locator.QhOf4G0', 'get_ServiceLocator_QhOf4G0Service', true],
            'App\\Controller\\AdminController::Categories' => ['privates', '.service_locator.64qvYlR', 'get_ServiceLocator_64qvYlRService', true],
            'App\\Controller\\AdminController::Couleurs' => ['privates', '.service_locator.VO4.glY', 'get_ServiceLocator_VO4_GlYService', true],
            'App\\Controller\\AdminController::ModificationCategorie' => ['privates', '.service_locator.pB6IJCx', 'get_ServiceLocator_PB6IJCxService', true],
            'App\\Controller\\AdminController::ModificationCouleur' => ['privates', '.service_locator.mbMnECa', 'get_ServiceLocator_MbMnECaService', true],
            'App\\Controller\\AdminController::ModificationOeuvre' => ['privates', '.service_locator.GkCVOPx', 'get_ServiceLocator_GkCVOPxService', true],
            'App\\Controller\\AdminController::Oeuvres' => ['privates', '.service_locator.Iq9hCXO', 'get_ServiceLocator_Iq9hCXOService', true],
            'App\\Controller\\AdminController::SuppressionCategories' => ['privates', '.service_locator.pB6IJCx', 'get_ServiceLocator_PB6IJCxService', true],
            'App\\Controller\\AdminController::SuppressionCouleurs' => ['privates', '.service_locator.mbMnECa', 'get_ServiceLocator_MbMnECaService', true],
            'App\\Controller\\AdminController::SuppressionOeuvres' => ['privates', '.service_locator.GkCVOPx', 'get_ServiceLocator_GkCVOPxService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.3HR315x', 'get_ServiceLocator_3HR315xService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.fJr0i09', 'get_ServiceLocator_FJr0i09Service', true],
            'App\\Controller\\SiteController::acceuil' => ['privates', '.service_locator.Mbfwcky', 'get_ServiceLocator_MbfwckyService', true],
            'App\\Controller\\SiteController::collection' => ['privates', '.service_locator.mFXv8NH', 'get_ServiceLocator_MFXv8NHService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:AjoutCategorie' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AdminController:AjoutCouleur' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AdminController:AjoutOeuvre' => ['privates', '.service_locator.QhOf4G0', 'get_ServiceLocator_QhOf4G0Service', true],
            'App\\Controller\\AdminController:Categories' => ['privates', '.service_locator.64qvYlR', 'get_ServiceLocator_64qvYlRService', true],
            'App\\Controller\\AdminController:Couleurs' => ['privates', '.service_locator.VO4.glY', 'get_ServiceLocator_VO4_GlYService', true],
            'App\\Controller\\AdminController:ModificationCategorie' => ['privates', '.service_locator.pB6IJCx', 'get_ServiceLocator_PB6IJCxService', true],
            'App\\Controller\\AdminController:ModificationCouleur' => ['privates', '.service_locator.mbMnECa', 'get_ServiceLocator_MbMnECaService', true],
            'App\\Controller\\AdminController:ModificationOeuvre' => ['privates', '.service_locator.GkCVOPx', 'get_ServiceLocator_GkCVOPxService', true],
            'App\\Controller\\AdminController:Oeuvres' => ['privates', '.service_locator.Iq9hCXO', 'get_ServiceLocator_Iq9hCXOService', true],
            'App\\Controller\\AdminController:SuppressionCategories' => ['privates', '.service_locator.pB6IJCx', 'get_ServiceLocator_PB6IJCxService', true],
            'App\\Controller\\AdminController:SuppressionCouleurs' => ['privates', '.service_locator.mbMnECa', 'get_ServiceLocator_MbMnECaService', true],
            'App\\Controller\\AdminController:SuppressionOeuvres' => ['privates', '.service_locator.GkCVOPx', 'get_ServiceLocator_GkCVOPxService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.3HR315x', 'get_ServiceLocator_3HR315xService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.fJr0i09', 'get_ServiceLocator_FJr0i09Service', true],
            'App\\Controller\\SiteController:acceuil' => ['privates', '.service_locator.Mbfwcky', 'get_ServiceLocator_MbfwckyService', true],
            'App\\Controller\\SiteController:collection' => ['privates', '.service_locator.mFXv8NH', 'get_ServiceLocator_MFXv8NHService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::AjoutCategorie' => '?',
            'App\\Controller\\AdminController::AjoutCouleur' => '?',
            'App\\Controller\\AdminController::AjoutOeuvre' => '?',
            'App\\Controller\\AdminController::Categories' => '?',
            'App\\Controller\\AdminController::Couleurs' => '?',
            'App\\Controller\\AdminController::ModificationCategorie' => '?',
            'App\\Controller\\AdminController::ModificationCouleur' => '?',
            'App\\Controller\\AdminController::ModificationOeuvre' => '?',
            'App\\Controller\\AdminController::Oeuvres' => '?',
            'App\\Controller\\AdminController::SuppressionCategories' => '?',
            'App\\Controller\\AdminController::SuppressionCouleurs' => '?',
            'App\\Controller\\AdminController::SuppressionOeuvres' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\SiteController::acceuil' => '?',
            'App\\Controller\\SiteController::collection' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:AjoutCategorie' => '?',
            'App\\Controller\\AdminController:AjoutCouleur' => '?',
            'App\\Controller\\AdminController:AjoutOeuvre' => '?',
            'App\\Controller\\AdminController:Categories' => '?',
            'App\\Controller\\AdminController:Couleurs' => '?',
            'App\\Controller\\AdminController:ModificationCategorie' => '?',
            'App\\Controller\\AdminController:ModificationCouleur' => '?',
            'App\\Controller\\AdminController:ModificationOeuvre' => '?',
            'App\\Controller\\AdminController:Oeuvres' => '?',
            'App\\Controller\\AdminController:SuppressionCategories' => '?',
            'App\\Controller\\AdminController:SuppressionCouleurs' => '?',
            'App\\Controller\\AdminController:SuppressionOeuvres' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\SiteController:acceuil' => '?',
            'App\\Controller\\SiteController:collection' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
