<?php

namespace ContainerPuoMt34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MFXv8NHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mFXv8NH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mFXv8NH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cacheManager' => ['services', 'liip_imagine.cache.manager', 'getLiipImagine_Cache_ManagerService', false],
            'catRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'categorie' => ['privates', '.errored..service_locator.mFXv8NH.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.mFXv8NH": it references class "App\\Entity\\Categorie" but no such service exists.'],
        ], [
            'cacheManager' => '?',
            'catRepo' => 'App\\Repository\\CategorieRepository',
            'categorie' => 'App\\Entity\\Categorie',
        ]);
    }
}
