<?php

namespace ContainerPuoMt34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VO4_GlYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VO4.glY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VO4.glY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'couleurRepo' => ['privates', 'App\\Repository\\CouleurRepository', 'getCouleurRepositoryService', true],
        ], [
            'couleurRepo' => 'App\\Repository\\CouleurRepository',
        ]);
    }
}
