<?php

namespace ContainerPuoMt34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Iq9hCXOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Iq9hCXO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Iq9hCXO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'oeuvreRepo' => ['privates', 'App\\Repository\\OeuvreRepository', 'getOeuvreRepositoryService', true],
        ], [
            'oeuvreRepo' => 'App\\Repository\\OeuvreRepository',
        ]);
    }
}
