<?php

namespace ContainerPuoMt34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcceuilTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AcceuilType' shared autowired service.
     *
     * @return \App\Form\AcceuilType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AcceuilType.php';

        return $container->privates['App\\Form\\AcceuilType'] = new \App\Form\AcceuilType();
    }
}
