<?php

namespace ContainerPuoMt34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouleurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mbMnECa.App\Entity\Couleur' shared service.
     *
     * @return \App\Entity\Couleur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mbMnECa": it references class "App\\Entity\\Couleur" but no such service exists.');
    }
}
