<?php

namespace ContainerPuoMt34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOeuvreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GkCVOPx.App\Entity\Oeuvre' shared service.
     *
     * @return \App\Entity\Oeuvre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.GkCVOPx": it references class "App\\Entity\\Oeuvre" but no such service exists.');
    }
}
