<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPuoMt34\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPuoMt34/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPuoMt34.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPuoMt34\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPuoMt34\App_KernelDevDebugContainer([
    'container.build_hash' => 'PuoMt34',
    'container.build_id' => 'c505e58c',
    'container.build_time' => 1639499328,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPuoMt34');
